"""Portfolio analytics via yfinance plus one LLM pass for observations."""

from __future__ import annotations

import asyncio
import json
import logging
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any

import yfinance as yf
from pydantic import BaseModel
from tenacity import retry, retry_if_exception_type, stop_after_attempt, wait_exponential

from src.llm.base import LLMClient
from src.models import (
    BenchmarkComparison,
    ConcentrationRisk,
    Observation,
    Performance,
    PortfolioHealthResult,
)

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "This analysis is generated by an AI system and is for informational purposes only. "
    "It does not constitute investment advice, a recommendation to buy or sell any security, "
    "or a solicitation of any investment. Past performance is not indicative of future results. "
    "Please consult a qualified financial adviser before making investment decisions."
)

DEFAULT_BENCHMARK_RETURN_PCT = 14.2


class _ObservationList(BaseModel):
    observations: list[Observation]


@dataclass
class ParsedProfile:
    user_id: str
    name: str
    age: int
    country: str
    base_currency: str
    risk_profile: str
    positions: list[dict[str, Any]]
    preferences: dict[str, Any]


def _parse_profile(user: dict) -> ParsedProfile:
    return ParsedProfile(
        user_id=str(user.get("user_id") or "unknown"),
        name=str(user.get("name") or ""),
        age=int(user.get("age") or 0),
        country=str(user.get("country") or ""),
        base_currency=str(user.get("base_currency") or "USD").upper(),
        risk_profile=str(user.get("risk_profile") or "moderate").lower(),
        positions=list(user.get("positions") or []),
        preferences=dict(user.get("preferences") or {}),
    )


def _benchmark_preference(prefs: dict[str, Any]) -> str:
    return str(prefs.get("preferred_benchmark") or "S&P 500")


def _benchmark_ticker(name: str) -> str:
    key = name.strip().upper()
    if "FTSE" in key:
        return "ISF.L"
    if "NIKKEI" in key:
        return "EWJ"
    if "MSCI" in key and "WORLD" in key:
        return "URTH"
    if key == "QQQ" or "NASDAQ-100" in key:
        return "QQQ"
    if "S&P" in name.upper() or "SP500" in key.replace(" ", "") or key == "SP500":
        return "SPY"
    return "SPY"


def _rule_based_build_observations(age: int, risk: str) -> list[Observation]:
    risk = risk.lower()
    obs: list[Observation] = []
    if age < 35:
        obs.append(
            Observation(
                severity="info",
                text=(
                    "You're early in your investing horizon — prioritizing broad diversification "
                    "often beats picking individual names until your plan is clear."
                ),
            )
        )
    elif age >= 55:
        obs.append(
            Observation(
                severity="info",
                text=(
                    "Closer to or in retirement, many investors emphasize steadier income "
                    "and downside resilience alongside growth."
                ),
            )
        )

    if risk == "conservative":
        obs.append(
            Observation(
                severity="info",
                text=(
                    "A conservative path usually blends high-quality bonds and dividend-focused "
                    "equity funds before reaching for volatile sectors."
                ),
            )
        )
        obs.append(
            Observation(
                severity="warning",
                text=(
                    "Keep 3–6 months of expenses in cash or equivalent before funding brokerage "
                    "contributions — that emergency buffer protects the rest of your plan."
                ),
            )
        )
    elif risk == "aggressive":
        obs.append(
            Observation(
                severity="warning",
                text=(
                    "Higher growth targets belong next to a clear risk budget — decide how much "
                    "you can afford to see fluctuate before you size thematic bets."
                ),
            )
        )
        obs.append(
            Observation(
                severity="info",
                text=(
                    "Core holdings in global index ETFs can anchor an aggressive sleeve while "
                    "you experiment with smaller satellite positions."
                ),
            )
        )
    else:
        obs.append(
            Observation(
                severity="info",
                text=(
                    "A moderate starter portfolio often uses one broad equity index ETF plus "
                    "an aggregate bond fund, rebalanced on a simple calendar."
                ),
            )
        )
        obs.append(
            Observation(
                severity="warning",
                text=(
                    "Fund an emergency cash cushion first; it keeps you from selling investments "
                    "when unexpected bills arrive."
                ),
            )
        )

    obs.append(
        Observation(
            severity="info",
            text=(
                "When you're ready, automate a small monthly contribution — consistency matters "
                "more than perfect timing for long horizons."
            ),
        )
    )
    return obs[:4]


def build_guidance_response(user: dict) -> PortfolioHealthResult:
    """Empty book: rule-based copy only, no LLM."""
    p = _parse_profile(user)
    benchmark_name = _benchmark_preference(p.preferences)
    observations = _rule_based_build_observations(p.age, p.risk_profile)

    risk_txt = p.risk_profile.title()
    first = (p.name or "").strip().split()[0] if (p.name or "").strip() else ""
    greet = f"Welcome, {first}. " if first else "Welcome. "
    build_guidance = (
        f"{greet}You don't hold any positions yet — that's a clean slate. "
        f"As someone with a {risk_txt} profile{f' at age {p.age}' if p.age else ''}, "
        "consider starting with a tiny recurring investment into one broad-market ETF aligned with your benchmark preference, "
        "keep emergency savings separate, and only add satellite positions once the core is funded. "
        "We're here when you want to stress-test a first allocation size."
    )

    return PortfolioHealthResult(
        concentration_risk=ConcentrationRisk(
            top_position_pct=0.0,
            top_3_positions_pct=0.0,
            flag="low",
        ),
        performance=Performance(
            total_return_pct=0.0,
            annualized_return_pct=0.0,
            cost_basis_total=0.0,
            current_value_total=0.0,
        ),
        benchmark_comparison=BenchmarkComparison(
            benchmark=benchmark_name,
            portfolio_return_pct=0.0,
            benchmark_return_pct=0.0,
            alpha_pct=0.0,
        ),
        observations=observations,
        disclaimer=DISCLAIMER,
        build_guidance=build_guidance,
    )


def _parse_date(iso: str) -> datetime | None:
    try:
        return datetime.fromisoformat(iso).replace(tzinfo=timezone.utc)
    except Exception:
        return None


def _close_usd_for_currency(amount_local: float, currency: str, fx: dict[str, float]) -> float:
    c = currency.upper()
    if c == "USD":
        return float(amount_local)
    if c == "EUR":
        return float(amount_local) * fx.get("EURUSD", 1.0)
    if c == "GBP":
        return float(amount_local) * fx.get("GBPUSD", 1.0)
    if c == "JPY":
        # USDJPY = yen per 1 USD → USD = JPY / USDJPY
        return float(amount_local) / fx.get("USDJPY", 150.0)
    return float(amount_local)


def _thread_last_close(symbol: str) -> float | None:
    try:
        t = yf.Ticker(symbol)
        hist = t.history(period="5d", auto_adjust=True)
        if hist is None or hist.empty:
            fi = getattr(t, "fast_info", None)
            if fi is not None and getattr(fi, "last_price", None):
                return float(fi.last_price)
            return None
        return float(hist["Close"].dropna().iloc[-1])
    except Exception as e:
        logger.debug("Price fetch failed for %s: %s", symbol, e)
        return None


async def _snapshot_fx_to_usd() -> dict[str, float]:
    async def one(sym: str) -> tuple[str, float | None]:
        val = await asyncio.to_thread(_thread_last_close, sym)
        return sym, val

    pairs = [("EURUSD=X", "EURUSD"), ("GBPUSD=X", "GBPUSD"), ("USDJPY=X", "USDJPY")]
    out: dict[str, float] = {}
    results = await asyncio.gather(*[one(sym) for sym, _ in pairs])
    defaults = {"EURUSD": 1.08, "GBPUSD": 1.27, "USDJPY": 150.0}
    for (sym, key), (_s, val) in zip(pairs, results):
        out[key] = float(val) if val is not None else defaults[key]
    return out


@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=0.5, min=0.5, max=4),
    retry=retry_if_exception_type(Exception),
    reraise=False,
)
async def _fetch_with_retry(tickers: list[str]) -> dict[str, float | None]:
    async def fetch_sym(sym: str) -> tuple[str, float | None]:
        px = await asyncio.to_thread(_thread_last_close, sym)
        return sym, px

    fetched = await asyncio.gather(*[fetch_sym(t) for t in tickers])
    prices = {sym: px for sym, px in fetched}
    if tickers and all(v is None for v in prices.values()):
        raise RuntimeError("all yfinance quote fetches returned None")
    return prices


async def _fetch_prices(positions: list[dict]) -> tuple[dict[str, float], list[str]]:
    """Last close per ticker in Yahoo's listing currency; warns when falling back to ``avg_cost``."""
    tickers = list({str(p.get("ticker") or "").strip() for p in positions if p.get("ticker")})
    warnings: list[str] = []
    prices_local: dict[str, float] = {}

    fetched_map: dict[str, float | None]
    try:
        fetched_map = await _fetch_with_retry(tickers)
    except Exception as e:
        logger.debug("yfinance retry wrapper failed: %s", e)
        fetched_map = {}

    for sym in tickers:
        px = fetched_map.get(sym)
        if px is None:
            # avg_cost matches position currency when quote is missing
            pcost = next((p for p in positions if str(p.get("ticker")) == sym), None)
            fb = float(pcost["avg_cost"]) if pcost and pcost.get("avg_cost") is not None else 0.0
            prices_local[sym] = fb
            warnings.append(
                f"Live quote unavailable for {sym}; using average cost ({fb:.4g}) as a placeholder price."
            )
        else:
            prices_local[sym] = px

    return prices_local, warnings


def _compute_concentration(positions_with_values: list[dict]) -> ConcentrationRisk:
    totals = [float(p["current_value"]) for p in positions_with_values]
    total = sum(totals)
    if total <= 0:
        return ConcentrationRisk(top_position_pct=0.0, top_3_positions_pct=0.0, flag="low")
    sorted_tv = sorted(totals, reverse=True)
    top1 = sorted_tv[0] / total * 100.0
    top3 = sum(sorted_tv[:3]) / total * 100.0
    if top1 < 25:
        flag = "low"
    elif top1 <= 40:
        flag = "medium"
    else:
        flag = "high"
    return ConcentrationRisk(
        top_position_pct=round(top1, 2),
        top_3_positions_pct=round(top3, 2),
        flag=flag,
    )


def _compute_performance(
    positions: list[dict],
    prices_local: dict[str, float],
    fx_to_usd: dict[str, float],
) -> tuple[Performance, datetime | None]:
    """Totals in USD; cost basis converted with spot FX (no historical FX)."""
    total_cost = 0.0
    total_current = 0.0
    oldest: datetime | None = None

    for pos in positions:
        ticker = str(pos.get("ticker") or "")
        qty = float(pos.get("quantity") or 0.0)
        avg_cost = float(pos.get("avg_cost") or 0.0)
        cur = str(pos.get("currency") or "USD").upper()
        purchased_at = pos.get("purchased_at")
        if isinstance(purchased_at, str):
            d = _parse_date(purchased_at)
            if d and (oldest is None or d < oldest):
                oldest = d

        price_local = float(prices_local.get(ticker, avg_cost))
        cost_usd = qty * _close_usd_for_currency(avg_cost, cur, fx_to_usd)
        current_usd = qty * _close_usd_for_currency(price_local, cur, fx_to_usd)
        total_cost += cost_usd
        total_current += current_usd

    if total_cost <= 0:
        return (
            Performance(
                total_return_pct=0.0,
                annualized_return_pct=0.0,
                cost_basis_total=0.0,
                current_value_total=round(total_current, 2),
            ),
            oldest,
        )

    total_return_pct = (total_current / total_cost - 1.0) * 100.0
    now = datetime.now(timezone.utc)
    years = 1.0 / 365.25
    if oldest:
        years = max((now - oldest).days / 365.25, 1.0 / 365.25)
    tr = total_current / total_cost
    annualized = (tr ** (1.0 / years) - 1.0) * 100.0

    return (
        Performance(
            total_return_pct=round(total_return_pct, 2),
            annualized_return_pct=round(annualized, 2),
            cost_basis_total=round(total_cost, 2),
            current_value_total=round(total_current, 2),
        ),
        oldest,
    )


def _period_return_pct(symbol: str, start: datetime, end: datetime) -> float | None:
    """Total return for ``symbol`` between ``start`` and ``end``.

    yfinance's batch ``download`` endpoint has been flaky upstream; ``Ticker.history``
    succeeds far more reliably for the same windows. We fall through to a coarse
    period-based query if the explicit date range comes back empty.
    """
    def _try_history(t: yf.Ticker, **kwargs) -> float | None:
        try:
            df = t.history(auto_adjust=True, **kwargs)
        except Exception as e:
            logger.debug("Benchmark history call failed for %s (%s): %s", symbol, kwargs, e)
            return None
        if df is None or df.empty:
            return None
        closes = df["Close"].dropna()
        if closes.empty:
            return None
        first = float(closes.iloc[0])
        last = float(closes.iloc[-1])
        if first <= 0:
            return None
        return (last / first - 1.0) * 100.0

    try:
        ticker = yf.Ticker(symbol)
        end_adj = end + timedelta(days=1)
        # Explicit date range first
        pct = _try_history(
            ticker,
            start=start.strftime("%Y-%m-%d"),
            end=end_adj.strftime("%Y-%m-%d"),
        )
        if pct is not None:
            return pct

        # Coarse fallback — pick the smallest yfinance period that covers the window
        days = max(1, (end - start).days)
        period = (
            "5d" if days <= 7
            else "1mo" if days <= 31
            else "3mo" if days <= 93
            else "6mo" if days <= 186
            else "1y" if days <= 380
            else "2y" if days <= 760
            else "5y"
        )
        return _try_history(ticker, period=period)
    except Exception as e:
        logger.debug("Benchmark fetch failed for %s: %s", symbol, e)
        return None


async def _compute_benchmark(
    performance: Performance,
    benchmark_name: str,
    oldest_purchase_date: datetime | None,
) -> tuple[BenchmarkComparison, bool]:
    """Bench vs portfolio over ~same window; second flag = series unavailable (placeholder return used)."""
    portfolio_return = performance.total_return_pct
    symbol = _benchmark_ticker(benchmark_name)
    end = datetime.now(timezone.utc)
    start = oldest_purchase_date or end

    bench_pct = await asyncio.to_thread(_period_return_pct, symbol, start, end)
    used_default = False
    if bench_pct is None:
        bench_pct = DEFAULT_BENCHMARK_RETURN_PCT
        used_default = True

    alpha = portfolio_return - bench_pct

    return (
        BenchmarkComparison(
            benchmark=benchmark_name,
            portfolio_return_pct=round(portfolio_return, 2),
            benchmark_return_pct=round(float(bench_pct), 2),
            alpha_pct=round(alpha, 2),
        ),
        used_default,
    )


def _default_observations() -> list[Observation]:
    return [
        Observation(
            severity="info",
            text="Portfolio totals were computed from latest available prices — verify figures against your custodian.",
        ),
        Observation(
            severity="warning",
            text="Concentration and performance numbers change daily; revisit after material deposits or trades.",
        ),
    ]


async def _generate_observations(
    user: dict,
    concentration: ConcentrationRisk,
    performance: Performance,
    benchmark: BenchmarkComparison,
    llm: LLMClient,
) -> list[Observation]:
    system = (
        "You are a plain-language financial health analyst for a wealth management app. "
        "Your audience is a novice investor. Rules:\n"
        "- Maximum 4 observations\n"
        "- Surface the 1–2 things that matter most — not every metric\n"
        "- Use plain language. No jargon without explanation.\n"
        "- For concentration risk top_position_pct > 40%: always include a warning observation\n"
        "- Tailor to risk_profile: conservative users → weight yield and capital preservation\n"
        "- Each observation must reference specific numbers from the data\n"
        '- Return ONLY valid JSON array: [{"severity":"info|warning|critical","text":"..."}] — no markdown.'
    )
    payload = {
        "user_summary": {
            "risk_profile": user.get("risk_profile"),
            "age": user.get("age"),
            "base_currency": user.get("base_currency"),
        },
        "concentration": concentration.model_dump(),
        "performance": performance.model_dump(),
        "benchmark": benchmark.model_dump(),
    }
    user_msg = json.dumps(payload, ensure_ascii=False)

    try:
        raw = await llm.complete(
            [{"role": "system", "content": system}, {"role": "user", "content": user_msg}],
            response_model=_ObservationList,
            temperature=0.3,
            max_tokens=900,
        )
        if not isinstance(raw, _ObservationList):
            raise TypeError("LLM returned non-_ObservationList response")
        out = raw.observations[:4]
        if concentration.top_position_pct > 40 and not any(
            "concentrat" in o.text.lower() or "nvda" in o.text.lower() for o in out
        ):
            out.insert(
                0,
                Observation(
                    severity="warning",
                    text=(
                        f"Roughly {concentration.top_position_pct:.1f}% of your portfolio sits in one "
                        "holding — well above the 40% threshold many planners treat as elevated single-stock risk."
                    ),
                ),
            )
        return out[:4] if out else _default_observations()
    except Exception:
        logger.exception("Observation LLM failed; using defaults")
        defaults = _default_observations()
        if concentration.top_position_pct > 40:
            defaults.insert(
                0,
                Observation(
                    severity="warning",
                    text=(
                        f"About {concentration.top_position_pct:.1f}% of portfolio value is in your largest position — "
                        "consider trimming or hedging if that exceeds your comfort zone."
                    ),
                ),
            )
        return defaults[:4]


class PortfolioHealthAgent:
    def __init__(self, llm: LLMClient) -> None:
        self._llm = llm

    async def run(self, user: dict) -> PortfolioHealthResult:
        try:
            profile = _parse_profile(user)
            if not profile.positions:
                return build_guidance_response(user)

            fx = await _snapshot_fx_to_usd()
            prices_local, price_warnings = await _fetch_prices(profile.positions)

            positions_with_values: list[dict[str, Any]] = []
            for pos in profile.positions:
                ticker = str(pos.get("ticker") or "")
                qty = float(pos.get("quantity") or 0.0)
                cur = str(pos.get("currency") or "USD").upper()
                px_loc = float(prices_local.get(ticker, float(pos.get("avg_cost") or 0.0)))
                current_usd = qty * _close_usd_for_currency(px_loc, cur, fx)
                positions_with_values.append(
                    {
                        **pos,
                        "current_value": current_usd,
                    }
                )

            concentration = _compute_concentration(positions_with_values)
            performance, oldest = _compute_performance(profile.positions, prices_local, fx)

            benchmark_name = _benchmark_preference(profile.preferences)
            benchmark, bench_defaulted = await _compute_benchmark(
                performance, benchmark_name, oldest
            )

            observations = await _generate_observations(
                user,
                concentration,
                performance,
                benchmark,
                self._llm,
            )

            for w in price_warnings[:3]:
                observations.insert(0, Observation(severity="warning", text=w))

            if bench_defaulted:
                observations.insert(
                    0,
                    Observation(
                        severity="info",
                        text=(
                            f"Benchmark total return was unavailable live; using "
                            f"{DEFAULT_BENCHMARK_RETURN_PCT}% as a placeholder for comparison."
                        ),
                    ),
                )

            observations = observations[:8]

            return PortfolioHealthResult(
                concentration_risk=concentration,
                performance=performance,
                benchmark_comparison=benchmark,
                observations=observations,
                disclaimer=DISCLAIMER,
                build_guidance=None,
            )
        except Exception:
            logger.exception("PortfolioHealthAgent.run failed; returning minimal safe result")
            return PortfolioHealthResult(
                concentration_risk=ConcentrationRisk(
                    top_position_pct=0.0, top_3_positions_pct=0.0, flag="low"
                ),
                performance=Performance(
                    total_return_pct=0.0,
                    annualized_return_pct=0.0,
                    cost_basis_total=0.0,
                    current_value_total=0.0,
                ),
                benchmark_comparison=BenchmarkComparison(
                    benchmark="S&P 500",
                    portfolio_return_pct=0.0,
                    benchmark_return_pct=DEFAULT_BENCHMARK_RETURN_PCT,
                    alpha_pct=-DEFAULT_BENCHMARK_RETURN_PCT,
                ),
                observations=_default_observations(),
                disclaimer=DISCLAIMER,
                build_guidance=None,
            )


async def run(user: dict, llm: LLMClient) -> PortfolioHealthResult:
    return await PortfolioHealthAgent(llm).run(user)
