"""Portfolio analytics via yfinance plus one LLM pass for observations.

Sub-intent routing inside ``run`` selects a focused pipeline
(concentration / performance / benchmark / rebalance / tax-loss)
or the default full health check.
"""

from __future__ import annotations

import asyncio
import json
import re
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any

import yfinance as yf
from agno.agent import Agent
from pydantic import BaseModel
from tenacity import retry, retry_if_exception_type, stop_after_attempt, wait_exponential

from src.agents.agno_react import coerce_pydantic
from src.llm.agno_model import agno_allows_structured_output_with_tools, get_agno_model
from src.llm.base import LLMClient
from src.logging_config import get_logger
from src.mcp import calculator_mcp, portfolio_analytics_mcp, yfinance_mcp
from src.models import (
    BenchmarkComparison,
    ConcentrationRisk,
    Observation,
    Performance,
    PortfolioHealthResult,
)

logger = get_logger("agents.portfolio_health")

DISCLAIMER = (
    "This analysis is generated by an AI system and is for informational purposes only. "
    "It does not constitute investment advice, a recommendation to buy or sell any security, "
    "or a solicitation of any investment. Past performance is not indicative of future results. "
    "Please consult a qualified financial adviser before making investment decisions."
)

DEFAULT_BENCHMARK_RETURN_PCT = 14.2

# Sub-intent ordering matters: more specific phrasings checked first.
_SUB_INTENT_RULES: list[tuple[str, re.Pattern[str]]] = [
    # `\w*` after partial roots (e.g. ``rebalanc``) captures every inflection
    # ("rebalance", "rebalancing", …) without listing them all.
    ("tax_loss_harvesting", re.compile(
        r"\b(tax[\s-]?loss|tax[\s-]?harvest\w*|harvest\w*\s+losses|"
        r"tax\s+saving|capital\s+loss|wash\s+sale)\b", re.I)),
    ("rebalance_suggestion", re.compile(
        r"\b(rebalanc\w*|reallocat\w*|target\s+(weight|allocation)|"
        r"asset\s+allocation|drift|trim)\b", re.I)),
    ("benchmark_comparison", re.compile(
        r"\b(benchmark\w*|beating\s+(the\s+)?market|s&p|sp[\s-]?500|qqq|nasdaq|"
        r"index\s+fund|outperform\w*|underperform\w*|alpha)\b", re.I)),
    ("concentration_only", re.compile(
        r"\b(diversif\w*|concentrat\w*|exposure\s+to\s+one|"
        r"single[\s-]?(stock|holding)|top\s+holding|sector\s+concentration|"
        r"too\s+much\s+in)\b", re.I)),
    ("performance_only", re.compile(
        r"\b(return\w*|performance|gain\w*|loss\w*|p&l|"
        r"profit\w*|how\s+much\s+(have|did)\s+i\s+(make|earn|gain|lose))\b", re.I)),
]


_REBALANCE_TARGETS: dict[str, dict[str, float]] = {
    "aggressive":   {"equity": 0.90, "bonds": 0.10},
    "moderate":     {"equity": 0.70, "bonds": 0.30},
    "conservative": {"equity": 0.50, "bonds": 0.50},
}


# yfinance tickers that we treat as bonds for the equity-vs-bonds split.
_BOND_TICKERS = frozenset({"BND", "AGG", "TLT", "IEF", "SHY", "VGIT", "VGSH", "VGLT", "BNDW", "GOVT"})

# Rough sector-equivalent ETFs to suggest as wash-sale-safe replacements.
_SECTOR_REPLACEMENT_ETFS: dict[str, str] = {
    "Technology": "QQQ",
    "Communication Services": "VOX",
    "Healthcare": "XLV",
    "Financial Services": "XLF",
    "Consumer Cyclical": "XLY",
    "Consumer Defensive": "XLP",
    "Energy": "XLE",
    "Industrials": "XLI",
    "Real Estate": "VNQ",
    "Utilities": "XLU",
    "Basic Materials": "XLB",
}


class _ObservationList(BaseModel):
    observations: list[Observation]


def _detect_sub_intent(intent: str, query: str) -> str:
    """Pick a focused mode by keyword-matching against intent + raw query.
    Defaults to ``full_health_check`` when nothing distinctive matches.
    """
    text = f"{intent or ''} {query or ''}"
    for label, rx in _SUB_INTENT_RULES:
        if rx.search(text):
            return label
    return "full_health_check"


@dataclass
class ParsedProfile:
    user_id: str
    name: str
    age: int
    country: str
    base_currency: str
    risk_profile: str
    positions: list[dict[str, Any]]
    preferences: dict[str, Any]


def _parse_profile(user: dict) -> ParsedProfile:
    return ParsedProfile(
        user_id=str(user.get("user_id") or "unknown"),
        name=str(user.get("name") or ""),
        age=int(user.get("age") or 0),
        country=str(user.get("country") or ""),
        base_currency=str(user.get("base_currency") or "USD").upper(),
        risk_profile=str(user.get("risk_profile") or "moderate").lower(),
        positions=list(user.get("positions") or []),
        preferences=dict(user.get("preferences") or {}),
    )


def _benchmark_preference(prefs: dict[str, Any]) -> str:
    return str(prefs.get("preferred_benchmark") or "S&P 500")


def _benchmark_ticker(name: str) -> str:
    key = name.strip().upper()
    if "FTSE" in key:
        return "ISF.L"
    if "NIKKEI" in key:
        return "EWJ"
    if "MSCI" in key and "WORLD" in key:
        return "URTH"
    if key == "QQQ" or "NASDAQ-100" in key:
        return "QQQ"
    if "S&P" in name.upper() or "SP500" in key.replace(" ", "") or key == "SP500":
        return "SPY"
    return "SPY"


def _rule_based_build_observations(age: int, risk: str) -> list[Observation]:
    risk = risk.lower()
    obs: list[Observation] = []
    if age < 35:
        obs.append(
            Observation(
                severity="info",
                text=(
                    "You're early in your investing horizon — prioritizing broad diversification "
                    "often beats picking individual names until your plan is clear."
                ),
            )
        )
    elif age >= 55:
        obs.append(
            Observation(
                severity="info",
                text=(
                    "Closer to or in retirement, many investors emphasize steadier income "
                    "and downside resilience alongside growth."
                ),
            )
        )

    if risk == "conservative":
        obs.append(
            Observation(
                severity="info",
                text=(
                    "A conservative path usually blends high-quality bonds and dividend-focused "
                    "equity funds before reaching for volatile sectors."
                ),
            )
        )
        obs.append(
            Observation(
                severity="warning",
                text=(
                    "Keep 3–6 months of expenses in cash or equivalent before funding brokerage "
                    "contributions — that emergency buffer protects the rest of your plan."
                ),
            )
        )
    elif risk == "aggressive":
        obs.append(
            Observation(
                severity="warning",
                text=(
                    "Higher growth targets belong next to a clear risk budget — decide how much "
                    "you can afford to see fluctuate before you size thematic bets."
                ),
            )
        )
        obs.append(
            Observation(
                severity="info",
                text=(
                    "Core holdings in global index ETFs can anchor an aggressive sleeve while "
                    "you experiment with smaller satellite positions."
                ),
            )
        )
    else:
        obs.append(
            Observation(
                severity="info",
                text=(
                    "A moderate starter portfolio often uses one broad equity index ETF plus "
                    "an aggregate bond fund, rebalanced on a simple calendar."
                ),
            )
        )
        obs.append(
            Observation(
                severity="warning",
                text=(
                    "Fund an emergency cash cushion first; it keeps you from selling investments "
                    "when unexpected bills arrive."
                ),
            )
        )

    obs.append(
        Observation(
            severity="info",
            text=(
                "When you're ready, automate a small monthly contribution — consistency matters "
                "more than perfect timing for long horizons."
            ),
        )
    )
    return obs[:4]


def build_guidance_response(user: dict) -> PortfolioHealthResult:
    """Empty book: rule-based copy only, no LLM."""
    p = _parse_profile(user)
    benchmark_name = _benchmark_preference(p.preferences)
    observations = _rule_based_build_observations(p.age, p.risk_profile)

    risk_txt = p.risk_profile.title()
    first = (p.name or "").strip().split()[0] if (p.name or "").strip() else ""
    greet = f"Welcome, {first}. " if first else "Welcome. "
    build_guidance = (
        f"{greet}You don't hold any positions yet — that's a clean slate. "
        f"As someone with a {risk_txt} profile{f' at age {p.age}' if p.age else ''}, "
        "consider starting with a tiny recurring investment into one broad-market ETF aligned with your benchmark preference, "
        "keep emergency savings separate, and only add satellite positions once the core is funded. "
        "We're here when you want to stress-test a first allocation size."
    )

    return PortfolioHealthResult(
        concentration_risk=ConcentrationRisk(
            top_position_pct=0.0,
            top_3_positions_pct=0.0,
            flag="low",
        ),
        performance=Performance(
            total_return_pct=0.0,
            annualized_return_pct=0.0,
            cost_basis_total=0.0,
            current_value_total=0.0,
        ),
        benchmark_comparison=BenchmarkComparison(
            benchmark=benchmark_name,
            portfolio_return_pct=0.0,
            benchmark_return_pct=0.0,
            alpha_pct=0.0,
        ),
        observations=observations,
        disclaimer=DISCLAIMER,
        build_guidance=build_guidance,
    )


def _parse_date(iso: str) -> datetime | None:
    try:
        return datetime.fromisoformat(iso).replace(tzinfo=timezone.utc)
    except Exception:
        return None


def _close_usd_for_currency(amount_local: float, currency: str, fx: dict[str, float]) -> float:
    c = currency.upper()
    if c == "USD":
        return float(amount_local)
    if c == "EUR":
        return float(amount_local) * fx.get("EURUSD", 1.0)
    if c == "GBP":
        return float(amount_local) * fx.get("GBPUSD", 1.0)
    if c == "JPY":
        # USDJPY = yen per 1 USD → USD = JPY / USDJPY
        return float(amount_local) / fx.get("USDJPY", 150.0)
    return float(amount_local)


def _thread_last_close(symbol: str) -> float | None:
    try:
        t = yf.Ticker(symbol)
        hist = t.history(period="5d", auto_adjust=True)
        if hist is None or hist.empty:
            fi = getattr(t, "fast_info", None)
            if fi is not None and getattr(fi, "last_price", None):
                return float(fi.last_price)
            return None
        return float(hist["Close"].dropna().iloc[-1])
    except Exception as e:
        logger.debug("Price fetch failed for %s: %s", symbol, e)
        return None


async def _snapshot_fx_to_usd() -> dict[str, float]:
    async def one(sym: str) -> tuple[str, float | None]:
        val = await asyncio.to_thread(_thread_last_close, sym)
        return sym, val

    pairs = [("EURUSD=X", "EURUSD"), ("GBPUSD=X", "GBPUSD"), ("USDJPY=X", "USDJPY")]
    out: dict[str, float] = {}
    results = await asyncio.gather(*[one(sym) for sym, _ in pairs])
    defaults = {"EURUSD": 1.08, "GBPUSD": 1.27, "USDJPY": 150.0}
    for (sym, key), (_s, val) in zip(pairs, results):
        out[key] = float(val) if val is not None else defaults[key]
    return out


@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=0.5, min=0.5, max=4),
    retry=retry_if_exception_type(Exception),
    reraise=False,
)
async def _fetch_with_retry(tickers: list[str]) -> dict[str, float | None]:
    async def fetch_sym(sym: str) -> tuple[str, float | None]:
        px = await asyncio.to_thread(_thread_last_close, sym)
        return sym, px

    fetched = await asyncio.gather(*[fetch_sym(t) for t in tickers])
    prices = {sym: px for sym, px in fetched}
    if tickers and all(v is None for v in prices.values()):
        raise RuntimeError("all yfinance quote fetches returned None")
    return prices


async def _fetch_prices(positions: list[dict]) -> tuple[dict[str, float], list[str]]:
    """Last close per ticker in Yahoo's listing currency; warns when falling back to ``avg_cost``."""
    tickers = list({str(p.get("ticker") or "").strip() for p in positions if p.get("ticker")})
    warnings: list[str] = []
    prices_local: dict[str, float] = {}

    fetched_map: dict[str, float | None]
    try:
        fetched_map = await _fetch_with_retry(tickers)
    except Exception as e:
        logger.debug("yfinance retry wrapper failed: %s", e)
        fetched_map = {}

    for sym in tickers:
        px = fetched_map.get(sym)
        if px is None:
            # avg_cost matches position currency when quote is missing
            pcost = next((p for p in positions if str(p.get("ticker")) == sym), None)
            fb = float(pcost["avg_cost"]) if pcost and pcost.get("avg_cost") is not None else 0.0
            prices_local[sym] = fb
            warnings.append(
                f"Live quote unavailable for {sym}; using average cost ({fb:.4g}) as a placeholder price."
            )
        else:
            prices_local[sym] = px

    return prices_local, warnings


def _compute_concentration(positions_with_values: list[dict]) -> ConcentrationRisk:
    totals = [float(p["current_value"]) for p in positions_with_values]
    total = sum(totals)
    if total <= 0:
        return ConcentrationRisk(top_position_pct=0.0, top_3_positions_pct=0.0, flag="low")
    sorted_tv = sorted(totals, reverse=True)
    top1 = sorted_tv[0] / total * 100.0
    top3 = sum(sorted_tv[:3]) / total * 100.0
    if top1 < 25:
        flag = "low"
    elif top1 <= 40:
        flag = "medium"
    else:
        flag = "high"
    return ConcentrationRisk(
        top_position_pct=round(top1, 2),
        top_3_positions_pct=round(top3, 2),
        flag=flag,
    )


def _compute_performance(
    positions: list[dict],
    prices_local: dict[str, float],
    fx_to_usd: dict[str, float],
) -> tuple[Performance, datetime | None]:
    """Totals in USD; cost basis converted with spot FX (no historical FX)."""
    total_cost = 0.0
    total_current = 0.0
    oldest: datetime | None = None

    for pos in positions:
        ticker = str(pos.get("ticker") or "")
        qty = float(pos.get("quantity") or 0.0)
        avg_cost = float(pos.get("avg_cost") or 0.0)
        cur = str(pos.get("currency") or "USD").upper()
        purchased_at = pos.get("purchased_at")
        if isinstance(purchased_at, str):
            d = _parse_date(purchased_at)
            if d and (oldest is None or d < oldest):
                oldest = d

        price_local = float(prices_local.get(ticker, avg_cost))
        cost_usd = qty * _close_usd_for_currency(avg_cost, cur, fx_to_usd)
        current_usd = qty * _close_usd_for_currency(price_local, cur, fx_to_usd)
        total_cost += cost_usd
        total_current += current_usd

    if total_cost <= 0:
        return (
            Performance(
                total_return_pct=0.0,
                annualized_return_pct=0.0,
                cost_basis_total=0.0,
                current_value_total=round(total_current, 2),
            ),
            oldest,
        )

    total_return_pct = (total_current / total_cost - 1.0) * 100.0
    now = datetime.now(timezone.utc)
    years = 1.0 / 365.25
    if oldest:
        years = max((now - oldest).days / 365.25, 1.0 / 365.25)
    tr = total_current / total_cost
    annualized = (tr ** (1.0 / years) - 1.0) * 100.0

    return (
        Performance(
            total_return_pct=round(total_return_pct, 2),
            annualized_return_pct=round(annualized, 2),
            cost_basis_total=round(total_cost, 2),
            current_value_total=round(total_current, 2),
        ),
        oldest,
    )


def _period_return_pct(symbol: str, start: datetime, end: datetime) -> float | None:
    """Total return for ``symbol`` between ``start`` and ``end``.

    yfinance's batch ``download`` endpoint has been flaky upstream; ``Ticker.history``
    succeeds far more reliably for the same windows. We fall through to a coarse
    period-based query if the explicit date range comes back empty.
    """
    def _try_history(t: yf.Ticker, **kwargs) -> float | None:
        try:
            df = t.history(auto_adjust=True, **kwargs)
        except Exception as e:
            logger.debug("Benchmark history call failed for %s (%s): %s", symbol, kwargs, e)
            return None
        if df is None or df.empty:
            return None
        closes = df["Close"].dropna()
        if closes.empty:
            return None
        first = float(closes.iloc[0])
        last = float(closes.iloc[-1])
        if first <= 0:
            return None
        return (last / first - 1.0) * 100.0

    try:
        ticker = yf.Ticker(symbol)
        end_adj = end + timedelta(days=1)
        # Explicit date range first
        pct = _try_history(
            ticker,
            start=start.strftime("%Y-%m-%d"),
            end=end_adj.strftime("%Y-%m-%d"),
        )
        if pct is not None:
            return pct

        # Coarse fallback — pick the smallest yfinance period that covers the window
        days = max(1, (end - start).days)
        period = (
            "5d" if days <= 7
            else "1mo" if days <= 31
            else "3mo" if days <= 93
            else "6mo" if days <= 186
            else "1y" if days <= 380
            else "2y" if days <= 760
            else "5y"
        )
        return _try_history(ticker, period=period)
    except Exception as e:
        logger.debug("Benchmark fetch failed for %s: %s", symbol, e)
        return None


async def _compute_benchmark(
    performance: Performance,
    benchmark_name: str,
    oldest_purchase_date: datetime | None,
) -> tuple[BenchmarkComparison, bool]:
    """Bench vs portfolio over ~same window; second flag = series unavailable (placeholder return used)."""
    portfolio_return = performance.total_return_pct
    symbol = _benchmark_ticker(benchmark_name)
    end = datetime.now(timezone.utc)
    start = oldest_purchase_date or end

    bench_pct = await asyncio.to_thread(_period_return_pct, symbol, start, end)
    used_default = False
    if bench_pct is None:
        bench_pct = DEFAULT_BENCHMARK_RETURN_PCT
        used_default = True

    alpha = portfolio_return - bench_pct

    return (
        BenchmarkComparison(
            benchmark=benchmark_name,
            portfolio_return_pct=round(portfolio_return, 2),
            benchmark_return_pct=round(float(bench_pct), 2),
            alpha_pct=round(alpha, 2),
        ),
        used_default,
    )


def _default_observations() -> list[Observation]:
    return [
        Observation(
            severity="info",
            text="Portfolio totals were computed from latest available prices — verify figures against your custodian.",
        ),
        Observation(
            severity="warning",
            text="Concentration and performance numbers change daily; revisit after material deposits or trades.",
        ),
    ]


async def _generate_observations(
    user: dict,
    concentration: ConcentrationRisk,
    performance: Performance,
    benchmark: BenchmarkComparison,
    llm: LLMClient,
) -> list[Observation]:
    system = (
        "You are a plain-language financial health analyst for a wealth management app. "
        "Your audience is a novice investor. Rules:\n"
        "- Maximum 4 observations\n"
        "- Surface the 1–2 things that matter most — not every metric\n"
        "- Use plain language. No jargon without explanation.\n"
        "- For concentration risk top_position_pct > 40%: always include a warning observation\n"
        "- Tailor to risk_profile: conservative users → weight yield and capital preservation\n"
        "- Each observation must reference specific numbers from the data\n"
        '- Return ONLY valid JSON array: [{"severity":"info|warning|critical","text":"..."}] — no markdown.'
    )
    payload = {
        "user_summary": {
            "risk_profile": user.get("risk_profile"),
            "age": user.get("age"),
            "base_currency": user.get("base_currency"),
        },
        "concentration": concentration.model_dump(),
        "performance": performance.model_dump(),
        "benchmark": benchmark.model_dump(),
    }
    user_msg = json.dumps(payload, ensure_ascii=False)

    try:
        raw = await llm.complete(
            [{"role": "system", "content": system}, {"role": "user", "content": user_msg}],
            response_model=_ObservationList,
            temperature=0.3,
            max_tokens=900,
        )
        if not isinstance(raw, _ObservationList):
            raise TypeError("LLM returned non-_ObservationList response")
        out = raw.observations[:4]
        if concentration.top_position_pct > 40 and not any(
            "concentrat" in o.text.lower() or "nvda" in o.text.lower() for o in out
        ):
            out.insert(
                0,
                Observation(
                    severity="warning",
                    text=(
                        f"Roughly {concentration.top_position_pct:.1f}% of your portfolio sits in one "
                        "holding — well above the 40% threshold many planners treat as elevated single-stock risk."
                    ),
                ),
            )
        return out[:4] if out else _default_observations()
    except Exception:
        logger.exception("Observation LLM failed; using defaults")
        defaults = _default_observations()
        if concentration.top_position_pct > 40:
            defaults.insert(
                0,
                Observation(
                    severity="warning",
                    text=(
                        f"About {concentration.top_position_pct:.1f}% of portfolio value is in your largest position — "
                        "consider trimming or hedging if that exceeds your comfort zone."
                    ),
                ),
            )
        return defaults[:4]


class PortfolioHealthAgent:
    def __init__(self, llm: LLMClient) -> None:
        self._llm = llm
        self._agno_react_checked = False
        self._agno_react: Agent | None = None

    @staticmethod
    def _detect_sub_intent(intent: str, query: str) -> str:
        return _detect_sub_intent(intent, query)

    def _ensure_agno_react(self) -> Agent | None:
        if self._agno_react_checked:
            return self._agno_react
        self._agno_react_checked = True
        model = get_agno_model()
        if model is None:
            self._agno_react = None
            return None
        try:
            instructions = [
                "You are an expert portfolio health analyst for Finsight AI.",
                "Always fetch live prices before computing any metrics.",
                "Always compute concentration risk — flag anything above 40% as high risk.",
                "Always compare portfolio return against the user's preferred benchmark.",
                "Always include the regulatory disclaimer in every response.",
                "Surface the 1–2 most important insights, not every metric.",
                "Use plain language — your audience may not be finance experts.",
                "For empty portfolios return build guidance based on age and risk profile.",
            ]
            if not agno_allows_structured_output_with_tools():
                instructions = [
                    *instructions,
                    "After tool calls, respond with ONE minified JSON object matching "
                    "PortfolioHealthResult: concentration_risk, performance, benchmark_comparison, "
                    "observations (list of {severity,text}), disclaimer, optional build_guidance, "
                    "sub_intent, extras — no markdown fences.",
                ]
            kw: dict[str, Any] = {
                "name": "Portfolio Health Analyst",
                "model": model,
                "tools": [yfinance_mcp, portfolio_analytics_mcp, calculator_mcp],
                "instructions": instructions,
                "markdown": False,
                "debug_mode": True,
            }
            if agno_allows_structured_output_with_tools():
                kw["output_schema"] = PortfolioHealthResult
                kw["structured_outputs"] = True
            else:
                kw["structured_outputs"] = False
            self._agno_react = Agent(**kw)
        except Exception as e:
            logger.warning("Portfolio Agno Agent construction failed: %s", e)
            self._agno_react = None
        return self._agno_react

    def _build_user_context(self, user: dict, intent: str, query: str) -> str:
        p = _parse_profile(user)
        sub = self._detect_sub_intent(intent, query)
        bench = _benchmark_preference(p.preferences)
        lines = [
            f"Analyse portfolio health for {p.name or 'the investor'} "
            f"(age {p.age or 'unknown'}, {p.risk_profile} risk profile).",
            "",
            f"Classifier intent: {intent or '(none)'}",
            f"User query: {query or '(none)'}",
            f"Detected sub-task: {sub}",
            "",
            "Current positions:",
        ]
        if not p.positions:
            lines.append("  (none — empty book)")
        else:
            for pos in p.positions:
                t = str(pos.get("ticker") or "")
                q = pos.get("quantity", "")
                ac = pos.get("avg_cost", "")
                dt = pos.get("purchased_at", "")
                lines.append(f"  - {t}: {q} shares, avg cost {ac}, bought {dt}")
        lines.extend([
            "",
            f"Preferred benchmark: {bench}",
            f"Base currency: {p.base_currency}",
            "",
            "Fetch live prices via tools, compute concentration and performance vs benchmark, "
            "and return a complete PortfolioHealthResult matching the output schema.",
        ])
        return "\n".join(lines)

    async def run(
        self,
        user: dict,
        intent: str = "",
        query: str = "",
    ) -> PortfolioHealthResult:
        react = self._ensure_agno_react()
        if react is not None:
            try:
                ctx = self._build_user_context(user, intent, query)
                resp = await react.arun(ctx, stream=False)
                parsed = coerce_pydantic(resp, PortfolioHealthResult)
                if parsed is not None:
                    return parsed
            except Exception as e:
                logger.error("Portfolio Agno react error: %s", e)
        return await self._run_legacy(user, intent, query)

    async def _run_legacy(
        self,
        user: dict,
        intent: str = "",
        query: str = "",
    ) -> PortfolioHealthResult:
        """Sub-intent dispatcher used when no API key is configured or structured Agno output failed."""
        sub = self._detect_sub_intent(intent, query)
        if sub == "concentration_only":
            return await self._concentration_analysis(user)
        if sub == "performance_only":
            return await self._performance_analysis(user)
        if sub == "benchmark_comparison":
            return await self._benchmark_comparison(user)
        if sub == "rebalance_suggestion":
            return await self._rebalance_suggestion(user)
        if sub == "tax_loss_harvesting":
            return await self._tax_loss_harvesting(user)
        return await self._full_health_check(user)

    # -------------------- default: full health check --------------------
    async def _full_health_check(self, user: dict) -> PortfolioHealthResult:
        try:
            profile = _parse_profile(user)
            if not profile.positions:
                return build_guidance_response(user)

            fx = await _snapshot_fx_to_usd()
            prices_local, price_warnings = await _fetch_prices(profile.positions)

            positions_with_values: list[dict[str, Any]] = []
            for pos in profile.positions:
                ticker = str(pos.get("ticker") or "")
                qty = float(pos.get("quantity") or 0.0)
                cur = str(pos.get("currency") or "USD").upper()
                px_loc = float(prices_local.get(ticker, float(pos.get("avg_cost") or 0.0)))
                current_usd = qty * _close_usd_for_currency(px_loc, cur, fx)
                positions_with_values.append({**pos, "current_value": current_usd})

            concentration = _compute_concentration(positions_with_values)
            performance, oldest = _compute_performance(profile.positions, prices_local, fx)

            benchmark_name = _benchmark_preference(profile.preferences)

            # Run benchmark fetch + 3 portfolio_analytics MCP tools concurrently —
            # any single failure degrades to {"error": ...} without blocking the
            # rest of the pipeline.
            tickers = [str(p["ticker"]).upper() for p in positions_with_values if p.get("ticker")]
            total_value = sum(p["current_value"] for p in positions_with_values) or 1.0
            weights = [p["current_value"] / total_value for p in positions_with_values]

            (
                benchmark_pair,
                sector_payload,
                dividend_payload,
                geo_payload,
            ) = await asyncio.gather(
                _compute_benchmark(performance, benchmark_name, oldest),
                asyncio.to_thread(portfolio_analytics_mcp.sector_exposure, tickers, weights),
                asyncio.to_thread(portfolio_analytics_mcp.dividend_analysis, positions_with_values),
                asyncio.to_thread(portfolio_analytics_mcp.geographic_exposure, tickers, weights),
            )
            benchmark, bench_defaulted = benchmark_pair

            observations = await _generate_observations(
                user, concentration, performance, benchmark, self._llm,
            )

            for w in price_warnings[:3]:
                observations.insert(0, Observation(severity="warning", text=w))

            if bench_defaulted:
                observations.insert(
                    0,
                    Observation(
                        severity="info",
                        text=(
                            f"Benchmark total return was unavailable live; using "
                            f"{DEFAULT_BENCHMARK_RETURN_PCT}% as a placeholder for comparison."
                        ),
                    ),
                )

            # Surface concrete analytics flags in the observation feed.
            for sector in (sector_payload.get("overweight_sectors") or [])[:1]:
                observations.append(Observation(
                    severity="warning",
                    text=(
                        f"Sector concentration: {sector['exposure_pct']:.1f}% in "
                        f"{sector['sector']} (above 40% threshold)."
                    ),
                ))
            div_income = dividend_payload.get("annual_dividend_income")
            if isinstance(div_income, (int, float)) and div_income > 0:
                observations.append(Observation(
                    severity="info",
                    text=(
                        f"Projected dividend income: ${div_income:,.2f}/year "
                        f"(~${dividend_payload.get('projected_monthly_income', 0):,.2f}/month)."
                    ),
                ))
            if geo_payload.get("home_bias_flag"):
                top = geo_payload.get("top_country") or {}
                observations.append(Observation(
                    severity="warning",
                    text=(
                        f"Home-bias risk: {top.get('exposure_pct'):.1f}% concentrated in "
                        f"{top.get('country')}."
                    ),
                ))

            return PortfolioHealthResult(
                concentration_risk=concentration,
                performance=performance,
                benchmark_comparison=benchmark,
                observations=observations[:8],
                disclaimer=DISCLAIMER,
                build_guidance=None,
                sub_intent="full_health_check",
                extras={
                    "sector_exposure": sector_payload,
                    "dividend_analysis": dividend_payload,
                    "geographic_exposure": geo_payload,
                },
            )
        except Exception:
            logger.exception("PortfolioHealthAgent.run failed; returning minimal safe result")
            return PortfolioHealthResult(
                concentration_risk=ConcentrationRisk(
                    top_position_pct=0.0, top_3_positions_pct=0.0, flag="low"
                ),
                performance=Performance(
                    total_return_pct=0.0,
                    annualized_return_pct=0.0,
                    cost_basis_total=0.0,
                    current_value_total=0.0,
                ),
                benchmark_comparison=BenchmarkComparison(
                    benchmark="S&P 500",
                    portfolio_return_pct=0.0,
                    benchmark_return_pct=DEFAULT_BENCHMARK_RETURN_PCT,
                    alpha_pct=-DEFAULT_BENCHMARK_RETURN_PCT,
                ),
                observations=_default_observations(),
                disclaimer=DISCLAIMER,
                build_guidance=None,
                sub_intent="full_health_check",
                extras=None,
            )

    # -------------------- sub-intents --------------------
    async def _priced_positions(
        self, user: dict
    ) -> tuple[list[dict[str, Any]], dict[str, float], dict[str, float], list[str]]:
        """Common prep: live prices + FX + per-position USD values + warnings."""
        profile = _parse_profile(user)
        fx = await _snapshot_fx_to_usd()
        prices_local, warnings = await _fetch_prices(profile.positions)

        rows: list[dict[str, Any]] = []
        for pos in profile.positions:
            ticker = str(pos.get("ticker") or "").upper()
            qty = float(pos.get("quantity") or 0.0)
            cur = str(pos.get("currency") or "USD").upper()
            avg_cost = float(pos.get("avg_cost") or 0.0)
            px_loc = float(prices_local.get(ticker, avg_cost))
            current_usd = qty * _close_usd_for_currency(px_loc, cur, fx)
            cost_usd = qty * _close_usd_for_currency(avg_cost, cur, fx)
            rows.append({
                **pos,
                "ticker": ticker,
                "current_price_local": px_loc,
                "current_value": current_usd,
                "cost_basis_usd": cost_usd,
                "unrealised_pnl_usd": current_usd - cost_usd,
                "unrealised_pnl_pct": ((px_loc / avg_cost - 1.0) * 100.0) if avg_cost > 0 else 0.0,
            })
        return rows, prices_local, fx, warnings

    async def _concentration_analysis(self, user: dict) -> PortfolioHealthResult:
        """Top-position + sector breakdown using live yfinance sector lookups."""
        rows, prices_local, fx, warnings = await self._priced_positions(user)
        if not rows:
            return build_guidance_response(user)

        concentration = _compute_concentration(rows)
        total = sum(r["current_value"] for r in rows) or 1.0

        # Sector lookup in parallel — graceful failure to "Unknown".
        async def sector_for(ticker: str) -> str:
            def _blocking() -> str:
                try:
                    info = yf.Ticker(ticker).info or {}
                    return str(info.get("sector") or "Unknown")
                except Exception:
                    return "Unknown"
            return await asyncio.to_thread(_blocking)

        sectors_list = await asyncio.gather(*(sector_for(r["ticker"]) for r in rows))
        sector_weights: dict[str, float] = {}
        for r, sector in zip(rows, sectors_list):
            sector_weights[sector] = sector_weights.get(sector, 0.0) + (r["current_value"] / total * 100.0)

        sector_breakdown = sorted(
            [{"sector": s, "weight_pct": round(w, 2)} for s, w in sector_weights.items()],
            key=lambda x: x["weight_pct"],
            reverse=True,
        )
        top_sector = sector_breakdown[0] if sector_breakdown else {"sector": "Unknown", "weight_pct": 0.0}

        per_position = sorted(
            [{"ticker": r["ticker"], "weight_pct": round(r["current_value"] / total * 100.0, 2)} for r in rows],
            key=lambda x: x["weight_pct"],
            reverse=True,
        )

        observations: list[Observation] = []
        for w in warnings[:2]:
            observations.append(Observation(severity="warning", text=w))
        if concentration.top_position_pct > 40:
            observations.append(Observation(
                severity="warning",
                text=(
                    f"Top holding is {concentration.top_position_pct:.1f}% of book — "
                    f"well above the 40% single-stock concentration threshold."
                ),
            ))
        if top_sector["weight_pct"] > 50:
            observations.append(Observation(
                severity="warning",
                text=(
                    f"Sector concentration is high: {top_sector['weight_pct']:.1f}% sits in "
                    f"{top_sector['sector']} alone."
                ),
            ))
        if not observations:
            observations.append(Observation(
                severity="info",
                text=(
                    f"Diversification looks balanced — top holding {concentration.top_position_pct:.1f}% "
                    f"and largest sector ({top_sector['sector']}) at {top_sector['weight_pct']:.1f}%."
                ),
            ))

        return PortfolioHealthResult(
            concentration_risk=concentration,
            performance=Performance(
                total_return_pct=0.0, annualized_return_pct=0.0,
                cost_basis_total=0.0, current_value_total=round(total, 2),
            ),
            benchmark_comparison=BenchmarkComparison(
                benchmark=_benchmark_preference(_parse_profile(user).preferences),
                portfolio_return_pct=0.0, benchmark_return_pct=0.0, alpha_pct=0.0,
            ),
            observations=observations[:5],
            disclaimer=DISCLAIMER,
            build_guidance=None,
            sub_intent="concentration_only",
            extras={
                "sector_breakdown": sector_breakdown,
                "per_position_weights": per_position,
                "top_sector": top_sector,
            },
        )

    async def _performance_analysis(self, user: dict) -> PortfolioHealthResult:
        """Total return + best/worst performers + unrealised P&L split."""
        rows, prices_local, fx, warnings = await self._priced_positions(user)
        if not rows:
            return build_guidance_response(user)

        profile = _parse_profile(user)
        performance, _oldest = _compute_performance(profile.positions, prices_local, fx)

        ranked = sorted(rows, key=lambda r: r["unrealised_pnl_pct"], reverse=True)
        best = ranked[0] if ranked else None
        worst = ranked[-1] if ranked else None
        unrealised_gains = round(sum(r["unrealised_pnl_usd"] for r in rows if r["unrealised_pnl_usd"] > 0), 2)
        unrealised_losses = round(sum(r["unrealised_pnl_usd"] for r in rows if r["unrealised_pnl_usd"] < 0), 2)

        observations: list[Observation] = []
        for w in warnings[:2]:
            observations.append(Observation(severity="warning", text=w))
        observations.append(Observation(
            severity="info",
            text=(
                f"Portfolio total return is {performance.total_return_pct:+.2f}% "
                f"(annualised {performance.annualized_return_pct:+.2f}%)."
            ),
        ))
        if best and worst and best["ticker"] != worst["ticker"]:
            observations.append(Observation(
                severity="info",
                text=(
                    f"Best performer: {best['ticker']} {best['unrealised_pnl_pct']:+.2f}%. "
                    f"Worst performer: {worst['ticker']} {worst['unrealised_pnl_pct']:+.2f}%."
                ),
            ))

        return PortfolioHealthResult(
            concentration_risk=_compute_concentration(rows),
            performance=performance,
            benchmark_comparison=BenchmarkComparison(
                benchmark=_benchmark_preference(profile.preferences),
                portfolio_return_pct=performance.total_return_pct,
                benchmark_return_pct=0.0, alpha_pct=0.0,
            ),
            observations=observations[:5],
            disclaimer=DISCLAIMER,
            build_guidance=None,
            sub_intent="performance_only",
            extras={
                "best_position": (
                    {"ticker": best["ticker"], "pnl_pct": round(best["unrealised_pnl_pct"], 2),
                     "pnl_usd": round(best["unrealised_pnl_usd"], 2)} if best else None
                ),
                "worst_position": (
                    {"ticker": worst["ticker"], "pnl_pct": round(worst["unrealised_pnl_pct"], 2),
                     "pnl_usd": round(worst["unrealised_pnl_usd"], 2)} if worst else None
                ),
                "unrealised_gains_usd": unrealised_gains,
                "unrealised_losses_usd": unrealised_losses,
                "ranked_positions": [
                    {"ticker": r["ticker"], "pnl_pct": round(r["unrealised_pnl_pct"], 2),
                     "pnl_usd": round(r["unrealised_pnl_usd"], 2)}
                    for r in ranked
                ],
            },
        )

    async def _benchmark_comparison(self, user: dict) -> PortfolioHealthResult:
        """Side-by-side vs SPY, QQQ, and the user's preferred benchmark."""
        rows, prices_local, fx, warnings = await self._priced_positions(user)
        if not rows:
            return build_guidance_response(user)

        profile = _parse_profile(user)
        performance, oldest = _compute_performance(profile.positions, prices_local, fx)
        preferred = _benchmark_preference(profile.preferences)

        # Always compare against the standard pair plus whatever the user prefers.
        targets = [("S&P 500", "SPY"), ("QQQ", "QQQ"), (preferred, _benchmark_ticker(preferred))]
        # Dedup by symbol while preserving order.
        seen: set[str] = set()
        targets = [(n, s) for n, s in targets if not (s in seen or seen.add(s))]

        end = datetime.now(timezone.utc)
        start = oldest or end
        results = await asyncio.gather(*(
            asyncio.to_thread(_period_return_pct, sym, start, end) for _, sym in targets
        ))

        comparisons = []
        for (name, sym), bench_pct in zip(targets, results):
            rate = bench_pct if bench_pct is not None else DEFAULT_BENCHMARK_RETURN_PCT
            comparisons.append({
                "name": name,
                "symbol": sym,
                "benchmark_return_pct": round(float(rate), 2),
                "portfolio_return_pct": round(performance.total_return_pct, 2),
                "alpha_pct": round(performance.total_return_pct - float(rate), 2),
                "live_data": bench_pct is not None,
            })

        observations: list[Observation] = []
        for w in warnings[:2]:
            observations.append(Observation(severity="warning", text=w))
        for c in comparisons:
            sev = "info" if c["alpha_pct"] >= 0 else "warning"
            tag = "ahead of" if c["alpha_pct"] >= 0 else "behind"
            observations.append(Observation(
                severity=sev,
                text=(
                    f"{tag} {c['name']} by {abs(c['alpha_pct']):.2f}% "
                    f"(portfolio {c['portfolio_return_pct']:+.2f}% vs {c['benchmark_return_pct']:+.2f}%)."
                ),
            ))

        primary = comparisons[0]
        return PortfolioHealthResult(
            concentration_risk=_compute_concentration(rows),
            performance=performance,
            benchmark_comparison=BenchmarkComparison(
                benchmark=primary["name"],
                portfolio_return_pct=primary["portfolio_return_pct"],
                benchmark_return_pct=primary["benchmark_return_pct"],
                alpha_pct=primary["alpha_pct"],
            ),
            observations=observations[:6],
            disclaimer=DISCLAIMER,
            build_guidance=None,
            sub_intent="benchmark_comparison",
            extras={"comparisons": comparisons},
        )

    async def _rebalance_suggestion(self, user: dict) -> PortfolioHealthResult:
        """Equity-vs-bonds drift relative to risk-profile target + per-ticker trade list."""
        rows, prices_local, _fx, warnings = await self._priced_positions(user)
        if not rows:
            return build_guidance_response(user)

        profile = _parse_profile(user)
        target = _REBALANCE_TARGETS.get(profile.risk_profile, _REBALANCE_TARGETS["moderate"])
        total = sum(r["current_value"] for r in rows) or 1.0

        bonds_value = sum(r["current_value"] for r in rows if r["ticker"] in _BOND_TICKERS)
        equity_value = total - bonds_value
        current_split = {
            "equity": round(equity_value / total, 4),
            "bonds": round(bonds_value / total, 4),
        }
        drift = {k: round(current_split[k] - target[k], 4) for k in ("equity", "bonds")}

        # Pro-rate the asset-class target back across each held ticker so the
        # calculator can produce concrete per-ticker trades.
        bond_holdings = [r for r in rows if r["ticker"] in _BOND_TICKERS]
        equity_holdings = [r for r in rows if r["ticker"] not in _BOND_TICKERS]
        target_alloc: dict[str, float] = {}
        if equity_holdings:
            cur_eq_total = sum(r["current_value"] for r in equity_holdings) or 1.0
            for r in equity_holdings:
                share = r["current_value"] / cur_eq_total
                target_alloc[r["ticker"]] = target["equity"] * share * 100.0
        if bond_holdings:
            cur_bd_total = sum(r["current_value"] for r in bond_holdings) or 1.0
            for r in bond_holdings:
                share = r["current_value"] / cur_bd_total
                target_alloc[r["ticker"]] = target["bonds"] * share * 100.0

        calc_input = [
            {
                "ticker": r["ticker"],
                "current_value": r["current_value"],
                "current_pct": (r["current_value"] / total) * 100.0,
                "price": prices_local.get(r["ticker"], r.get("current_price_local") or 0.0),
            }
            for r in rows
        ]
        calc_payload = await asyncio.to_thread(
            calculator_mcp.portfolio_rebalance_trades, calc_input, target_alloc, total,
        )
        per_ticker_trades = calc_payload.get("actionable_trades") or []

        # Asset-class summary trades (kept for high-level reporting).
        trade_amount_usd = round(abs(drift["equity"]) * total, 2)
        action = "trim equity, add bonds" if drift["equity"] > 0 else "add equity, trim bonds"
        rebalance_trades = [
            {
                "action": "sell" if drift["equity"] > 0 else "buy",
                "asset_class": "equity",
                "amount_usd": trade_amount_usd,
            },
            {
                "action": "buy" if drift["equity"] > 0 else "sell",
                "asset_class": "bonds",
                "amount_usd": trade_amount_usd,
            },
        ] if abs(drift["equity"]) > 0.05 else []  # 5pp tolerance band

        observations: list[Observation] = []
        for w in warnings[:2]:
            observations.append(Observation(severity="warning", text=w))
        observations.append(Observation(
            severity="info",
            text=(
                f"{profile.risk_profile.title()} target: "
                f"{int(target['equity']*100)}% equity / {int(target['bonds']*100)}% bonds. "
                f"Current: {int(current_split['equity']*100)}% / {int(current_split['bonds']*100)}%."
            ),
        ))
        if rebalance_trades:
            observations.append(Observation(
                severity="warning",
                text=(
                    f"Drift exceeds 5pp — to realign {action} by approximately "
                    f"${trade_amount_usd:,.0f}."
                ),
            ))
        else:
            observations.append(Observation(
                severity="info",
                text="Allocation drift is within the 5pp tolerance band — no rebalance needed.",
            ))

        return PortfolioHealthResult(
            concentration_risk=_compute_concentration(rows),
            performance=Performance(
                total_return_pct=0.0, annualized_return_pct=0.0,
                cost_basis_total=0.0, current_value_total=round(total, 2),
            ),
            benchmark_comparison=BenchmarkComparison(
                benchmark=_benchmark_preference(profile.preferences),
                portfolio_return_pct=0.0, benchmark_return_pct=0.0, alpha_pct=0.0,
            ),
            observations=observations[:5],
            disclaimer=DISCLAIMER,
            build_guidance=None,
            sub_intent="rebalance_suggestion",
            extras={
                "risk_profile": profile.risk_profile,
                "target_allocation": target,
                "current_allocation": current_split,
                "drift": drift,
                "rebalance_trades": rebalance_trades,
                "per_ticker_trades": per_ticker_trades,
                "total_trade_value_usd": calc_payload.get("total_trade_value", 0.0),
            },
        )

    async def _tax_loss_harvesting(self, user: dict) -> PortfolioHealthResult:
        """Identify losers + estimate 30% tax saving + suggest sector-equivalent ETF replacements."""
        rows, _prices, _fx, warnings = await self._priced_positions(user)
        if not rows:
            return build_guidance_response(user)

        TAX_RATE = 0.30
        losers = [r for r in rows if r["unrealised_pnl_usd"] < 0]
        losers.sort(key=lambda r: r["unrealised_pnl_usd"])

        # Sector lookup in parallel → ETF replacement candidate per loser.
        async def sector_for(ticker: str) -> str:
            def _blocking() -> str:
                try:
                    info = yf.Ticker(ticker).info or {}
                    return str(info.get("sector") or "Unknown")
                except Exception:
                    return "Unknown"
            return await asyncio.to_thread(_blocking)

        sectors = await asyncio.gather(*(sector_for(r["ticker"]) for r in losers))
        candidates = []
        total_loss = 0.0
        for r, sector in zip(losers, sectors):
            loss_usd = r["unrealised_pnl_usd"]
            total_loss += loss_usd
            candidates.append({
                "ticker": r["ticker"],
                "loss_usd": round(loss_usd, 2),
                "loss_pct": round(r["unrealised_pnl_pct"], 2),
                "sector": sector,
                "replacement_etf": _SECTOR_REPLACEMENT_ETFS.get(sector, "VTI"),
                "wash_sale_note": (
                    "Avoid repurchasing the same security within 30 days to keep the loss deductible."
                ),
            })

        tax_saving_estimate = round(abs(total_loss) * TAX_RATE, 2)

        observations: list[Observation] = []
        for w in warnings[:2]:
            observations.append(Observation(severity="warning", text=w))
        if candidates:
            observations.append(Observation(
                severity="info",
                text=(
                    f"Found {len(candidates)} position(s) at a loss totalling "
                    f"${abs(total_loss):,.2f} — harvesting could offset roughly "
                    f"${tax_saving_estimate:,.2f} in taxes at a 30% rate."
                ),
            ))
            top = candidates[0]
            observations.append(Observation(
                severity="info",
                text=(
                    f"Largest loss: {top['ticker']} ({top['loss_pct']:+.2f}%). "
                    f"To preserve {top['sector']} exposure consider {top['replacement_etf']} as a "
                    f"wash-sale-safe replacement."
                ),
            ))
        else:
            observations.append(Observation(
                severity="info",
                text="No positions are currently at a loss — nothing to harvest right now.",
            ))

        total = sum(r["current_value"] for r in rows) or 0.0
        profile = _parse_profile(user)
        return PortfolioHealthResult(
            concentration_risk=_compute_concentration(rows),
            performance=Performance(
                total_return_pct=0.0, annualized_return_pct=0.0,
                cost_basis_total=0.0, current_value_total=round(total, 2),
            ),
            benchmark_comparison=BenchmarkComparison(
                benchmark=_benchmark_preference(profile.preferences),
                portfolio_return_pct=0.0, benchmark_return_pct=0.0, alpha_pct=0.0,
            ),
            observations=observations[:5],
            disclaimer=DISCLAIMER,
            build_guidance=None,
            sub_intent="tax_loss_harvesting",
            extras={
                "tax_rate_assumed": TAX_RATE,
                "total_unrealised_loss_usd": round(total_loss, 2),
                "estimated_tax_saving_usd": tax_saving_estimate,
                "harvest_candidates": candidates,
            },
        )


async def run(
    user: dict,
    llm: LLMClient,
    intent: str = "",
    query: str = "",
) -> PortfolioHealthResult:
    return await PortfolioHealthAgent(llm).run(user, intent=intent, query=query)
